#!/usr/bin/env node
/* tools/build-icons.mjs — dev-only (A27). Compiles public/assets/icons/*.svg → public/js/05-data-icons.js.
 *
 *   node tools/build-icons.mjs           regenerate the data file
 *   node tools/build-icons.mjs --check   exit 1 if the committed file differs from what the sources would produce (CI drift check)
 *
 * Each source is a 24×24 line icon using currentColor strokes. The compiler keeps only the inner markup and wraps it in
 * <symbol id="ic_<name>">; stroke style comes from the .ic CSS class (css/base.css) so one rule re-tints every icon.
 * Rules enforced here: viewBox 0 0 24 24 · no fixed colours · no <script>/<style>/on* attributes/href · sprite ≤ 60 KB (F.8).
 * Nothing in the runtime depends on this script: the generated file is committed (A27).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'public/assets/icons');
const OUT = path.join(ROOT, 'public/js/05-data-icons.js');
const BUDGET = 60 * 1024;
const check = process.argv.includes('--check');

const errors = [];
const symbols = [];
const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort();
const names = files.map((f) => f.replace(/\.svg$/, ''));

for (const file of files) {
  const name = file.replace(/\.svg$/, '');
  const raw = fs.readFileSync(path.join(SRC, file), 'utf8').trim();
  const m = raw.match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>$/);
  if (!m) { errors.push(`${file}: not a single <svg> element`); continue; }
  if (!/viewBox="0 0 24 24"/.test(m[1])) { errors.push(`${file}: viewBox must be "0 0 24 24"`); }
  const inner = m[2].replace(/\s*\n\s*/g, '').trim();
  if (/<(script|style|image|foreignObject)\b/i.test(inner)) { errors.push(`${file}: forbidden element`); }
  if (/\son[a-z]+\s*=|href\s*=|javascript:/i.test(inner)) { errors.push(`${file}: forbidden attribute`); }
  if (/(stroke|fill)="(?!none|currentColor)[^"]+"/i.test(inner)) { errors.push(`${file}: fixed colour (use currentColor / none)`); }
  if (!/^[a-z0-9_]+$/.test(name)) { errors.push(`${file}: file name must be [a-z0-9_]+`); }
  symbols.push(`<symbol id="ic_${name}" viewBox="0 0 24 24">${inner}</symbol>`);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" class="ic-sprite">${symbols.join('')}</svg>`;
if (sprite.length > BUDGET) { errors.push(`sprite is ${sprite.length} bytes; budget is ${BUDGET}`); }
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }

const body = `/* GENERATED by tools/build-icons.mjs from public/assets/icons/*.svg — DO NOT EDIT BY HAND.
   ${names.length} symbols · ${sprite.length} bytes (budget 60 KB). Injected once into the DOM by RR.app.boot (never fetched: file:// safe). */
(function (RR) {
  'use strict';
  RR.data.iconNames = ${JSON.stringify(names.map((n) => 'ic_' + n))};
  RR.data.iconSprite = ${JSON.stringify(sprite)};
})(window.RR);
`;

if (check) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== body) { console.error('05-data-icons.js is out of date. Run: node tools/build-icons.mjs'); process.exit(1); }
  console.log(`icons OK (${names.length} symbols, ${sprite.length} bytes)`);
} else {
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${names.length} symbols, ${sprite.length} bytes`);
}
