#!/usr/bin/env node
/* tools/build-scenes.mjs — dev-only (A27). Compiles public/assets/scenes/*.json → public/js/05-data-scenes.js.
 *
 *   node tools/build-scenes.mjs           regenerate
 *   node tools/build-scenes.mjs --check   exit 1 on drift (CI)
 *
 * Scene source grammar (viewBox is always 0 0 480 270; the renderer scales it to any size):
 *   ['r', x, y, w, h, fill, opacity?, radius?]        rectangle
 *   ['c', cx, cy, r, fill, opacity?]                  circle
 *   ['e', cx, cy, rx, ry, fill, opacity?]             ellipse
 *   ['p', d, fill, opacity?]                          filled path
 *   ['l', d, stroke, width, opacity?]                 stroked path (no fill)
 * Colour keys: t = category tint (palette) · k = ink · w = white · g = warm light. No raw colours: the renderer resolves
 * the keys, so a scene can be re-tinted by category, Fast Track mode or a premium theme (F.1).
 * Budgets (F.3/F.8): each scene ≤ 6 KB of code · all scenes ≤ 80 KB.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'public/assets/scenes');
const OUT = path.join(ROOT, 'public/js/05-data-scenes.js');
const PER_SCENE = 6 * 1024, TOTAL = 80 * 1024;
const TIER_A = ['scene_office', 'scene_hospital', 'scene_home_interior', 'scene_street_house', 'scene_storm_house', 'scene_bank_lobby',
                'scene_market_floor', 'scene_cafe', 'scene_wedding', 'scene_garage', 'scene_apartment_block', 'scene_news_desk'];
const FILLS = new Set(['t', 'k', 'w', 'g']);
const check = process.argv.includes('--check');

const errors = [];
const num = (v) => typeof v === 'number' && Number.isFinite(v);
const SHAPES = {                       // n = [min, max] arguments after the type tag · fill = index of the colour key in the array
  r: { n: [5, 7], fill: 5, nums: [1, 2, 3, 4] },
  c: { n: [4, 5], fill: 4, nums: [1, 2, 3] },
  e: { n: [5, 6], fill: 5, nums: [1, 2, 3, 4] },
  p: { n: [2, 3], fill: 2, nums: [] },
  l: { n: [3, 4], fill: 2, nums: [3] }
};

const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.json')).sort();
const scenes = {};
for (const file of files) {
  let def;
  try { def = JSON.parse(fs.readFileSync(path.join(SRC, file), 'utf8')); } catch (e) { errors.push(`${file}: invalid JSON (${e.message})`); continue; }
  const id = def.id;
  if (id !== file.replace(/\.json$/, '')) { errors.push(`${file}: id "${id}" must match the file name`); }
  if (!Array.isArray(def.shapes) || !def.shapes.length) { errors.push(`${file}: shapes[] required`); continue; }
  if (!def.label || !def.alt) { errors.push(`${file}: label and alt (accessible description) are required`); }
  def.shapes.forEach((s, i) => {
    const spec = SHAPES[s[0]];
    if (!spec) { errors.push(`${file}#${i}: unknown shape "${s[0]}"`); return; }
    const args = s.length - 1;
    if (args < spec.n[0] || args > spec.n[1]) { errors.push(`${file}#${i}: wrong argument count for "${s[0]}"`); }
    spec.nums.forEach((k) => { if (!num(s[k])) { errors.push(`${file}#${i}: argument ${k} must be a finite number`); } });
    if (!FILLS.has(s[spec.fill])) { errors.push(`${file}#${i}: colour key must be one of t k w g (got ${JSON.stringify(s[spec.fill])})`); }
    const opIdx = s[0] === 'r' ? 6 : (s[0] === 'c' ? 5 : (s[0] === 'e' ? 6 : (s[0] === 'p' ? 3 : 4)));
    if (s[opIdx] !== undefined && (!num(s[opIdx]) || s[opIdx] < 0 || s[opIdx] > 1)) { errors.push(`${file}#${i}: opacity must be 0..1`); }
    if ((s[0] === 'p' || s[0] === 'l') && !/^[MmLlHhVvCcSsQqTtAaZz0-9eE.,\s-]+$/.test(s[1])) { errors.push(`${file}#${i}: path data has illegal characters`); }
    if (s[0] === 'r' && (s[3] <= 0 || s[4] <= 0)) { errors.push(`${file}#${i}: rectangle has no area`); }
  });
  const bytes = JSON.stringify(def).length;
  if (bytes > PER_SCENE) { errors.push(`${file}: ${bytes} bytes exceeds the ${PER_SCENE}-byte per-scene budget`); }
  scenes[id] = { label: def.label, alt: def.alt, shapes: def.shapes };
}
for (const id of TIER_A) { if (!scenes[id]) { errors.push(`missing Tier-A scene ${id}`); } }
const ids = Object.keys(scenes).sort();

const body = `/* GENERATED by tools/build-scenes.mjs from public/assets/scenes/*.json — DO NOT EDIT BY HAND.
   ${ids.length} scenes. Rendered by RR.ui.scene.render (19-ui-art.js). Budget: ≤ 6 KB per scene, ≤ 80 KB total. */
(function (RR) {
  'use strict';
  RR.data.sceneIds = ${JSON.stringify(ids)};
  RR.data.scenes = ${JSON.stringify(scenes)};
})(window.RR);
`;
if (body.length > TOTAL) { errors.push(`scenes total ${body.length} bytes exceeds ${TOTAL}`); }
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }

if (check) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== body) { console.error('05-data-scenes.js is out of date. Run: node tools/build-scenes.mjs'); process.exit(1); }
  console.log(`scenes OK (${ids.length} scenes, ${body.length} bytes)`);
} else {
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${ids.length} scenes, ${body.length} bytes`);
}
